services:
  backend:
    build: ./backend
    ports:
      - '3000:3000'
    env_file:
      - backend/.env
    depends_on:
      - db
    networks:
      - app_network
    restart: "no"
  #   build: ./frontend
  #   ports:
  #     - '19000:19000'
  #   # env_file:
  #   #   - frontend/.env

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: boostcoach
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - app_network

volumes:
  db-data:

networks:
  app_network:
    driver: bridge
